# image: maven:3.8.3-openjdk-17

stages:
  - build
  - test

maven-build:
  stage: build
  tags:
    - ugrad
  script:
    - cd backend
    - mvn clean package -DskipTests
    # - "mvn package -f backend/pom.xml"
  # artifacts:
  #   paths:
  #     - target/surefire-reports/TEST-*.xml
  #   reports:
  #     junit:
  #       - target/surefire-reports/TEST-*.xml

test-job:
  stage: test
  script:
    - echo "Running tests (pretending actually)..."
    - sleep 10
    - echo "Fake test coverage is like 5%"