image: maven:3.8.3-openjdk-17

stages:
  - build

maven-build:
  stage: build
  script: "mvn package -f backend/pom.xml"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml