image: maven:3.8.3-openjdk-17

stages:
  - build
  - test

maven-build:
  stage: build
  script:
    - cd backend
    - mvn clean package -DskipTests
  #   - "mvn package -f backend/pom.xml"
  # artifacts:
  #   paths:
  #     - target/surefire-reports/TEST-*.xml
  #   reports:
  #     junit:
  #       - target/surefire-reports/TEST-*.xml

test-job:
  stage: test
  script:
    - cd backend
    - mvn clean verify